name: Deploy Sam-app
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        cd apis
        pip install -r requirements.txt
      working-directory: ./sam-app

    - name: Build and Deploy SAM application
      working-directory: ./sam-app
      run: |
        sam build
        sam deploy \
          --template-file template.yaml \
          --stack-name ${{ vars.STACK_NAME }} \
          --region ${{ secrets.AWS_REGION }} \
          --parameter-overrides \
            StateHost=${{ secrets.STATE_HOST }} \
            StateUser=${{ secrets.STATE_USER }} \
            StatePassword=${{ secrets.STATE_PASSWORD }} \
            StatePort=${{ secrets.STATE_PORT }} \
            StateDatabase=${{ secrets.STATE_DATABASE }} \
            RedirectUri=${{ secrets.REDIRECT_URI }} \
            JwtSecret=${{ secrets.JWT_SECRET }} \
            SecretKey=${{ secrets.SECRET_KEY }} \
            SMBDomain=${{ secrets.SMB_DOMAIN }} \
            SMTPServer=${{ secrets.SMTP_SERVER }} \
            SMTPPort=${{ secrets.SMTP_PORT }} \
            SMTPUsername=${{ secrets.SMTP_USERNAME }} \
            SMTPPassword=${{ secrets.SMTP_PASSWORD }} \
            SMTPFromEmail=${{ secrets.SMTP_FROM_EMAIL }} \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
