name: Deploy SAM Application

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout with submodules
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Configure AWS SAM CLI and AWS Credentials
      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::621422041465:role/GitHubActionsRole  # Adjust to your IAM role ARN
          role-session-name: sam-deployment-session-${{ env.BRANCH_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      # Install dependencies using requirements.txt
      - name: Install dependencies
        run: |
          cd apis
          pip install -r requirements.txt
        working-directory: ./sam-app

      # Build SAM application
      - name: Build SAM application
        run: sam build
        working-directory: ./sam-app

      # Deploy SAM application
      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name sam-app-${{ env.BRANCH_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --parameter-overrides \
              StateHost=${{ secrets.STATE_HOST }} \
              StateUser=${{ secrets.STATE_USER }} \
              StatePassword=${{ secrets.STATE_PASSWORD }} \
              StatePort=${{ secrets.STATE_PORT }} \
              StateDatabase=${{ secrets.STATE_DATABASE }} \
              RedirectUri=${{ secrets.REDIRECT_URI }} \
              JwtSecret=${{ secrets.JWT_SECRET }} \
              SecretKey=${{ secrets.SECRET_KEY }} \
              SMBDomain=${{ secrets.SMB_DOMAIN }} \
              SMTPServer=${{ secrets.SMTP_SERVER }} \
              SMTPPort=${{ secrets.SMTP_PORT }} \
              SMTPUsername=${{ secrets.SMTP_USERNAME }} \
              SMTPPassword=${{ secrets.SMTP_PASSWORD }} \
              SMTPFromEmail=${{ secrets.SMTP_FROM_EMAIL }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: ./sam-app
