name: Deploy SAM Application

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout with submodules
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Configure AWS SAM CLI and AWS Credentials
      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::621422041465:role/GitHubActionsRole  # Adjust to your IAM role ARN
          role-session-name: sam-deployment-session-${{ env.BRANCH_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      # Install dependencies using requirements.txt
      - name: Install dependencies
        run: |
          cd apis
          pip install -r requirements.txt
        working-directory: ./sam-app

      # Build SAM application
      - name: Build SAM application
        run: sam build
        working-directory: ./sam-app
        
      # Create parameters.json from environment variables dynamically
      - name: Set environment variables for secrets
        run: |
          # Create parameters.json from environment variables dynamically
          echo '{' > dynamic_parameters.json
          for var in $(compgen -e); do
            # Check if the variable name consists of letters, numbers, and underscores
            if [[ $var =~ ^[a-zA-Z0-9_]+$ ]]; then
              value=$(printenv $var)
              key=$(echo $var | sed 's/_/-/g')  # Replace underscores with hyphens if needed
              echo "\"$key\": \"$value\"," >> dynamic_parameters.json
            fi
          done
          echo '}' >> dynamic_parameters.json
          cat dynamic_parameters.json

      # Deploy SAM application
      - name: Deploy SAM application
        run: |
          ls -l dynamic_parameters.json
          cat dynamic_parameters.json
          
          sam deploy \
            --stack-name sam-app-${{ env.BRANCH_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --parameter-overrides $(cat dynamic_parameters.json | jq -r '. | to_entries[] | "ParameterKey=\(.key),ParameterValue=\(.value)"') \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        working-directory: ./sam-app
